project_id = "ocpmhsquwsdaauflbygf"

[functions.perplexity-restaurant-info]
verify_jwt = false

[functions.determine-cuisine]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://preview--resto-radar-reviews-hub.lovable.app"
additional_redirect_urls = ["https://preview--resto-radar-reviews-hub.lovable.app/**", "http://localhost:3000/**", "http://localhost:5173/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[storage]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.geocode]
verify_jwt = true

[edge_functions.set-mapbox-token]
verify_jwt = true

[edge_functions.restaurant-discovery]
verify_jwt = false

[edge_functions.delete-user-account]
verify_jwt = true

[edge_functions.cache-warmer]
verify_jwt = true

[edge_functions.amadeus-api]
verify_jwt = false

[edge_functions.amadeus-enhanced-flight-api]
verify_jwt = false

[edge_functions.tripadvisor-api]
verify_jwt = false

[edge_functions.google-photo-proxy]
verify_jwt = false
