// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buimqicgrupxbcvbrhwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aW1xaWNncnVweGJjdmJyaHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQwMzgsImV4cCI6MjA2ODM1MDAzOH0.UiLoOPpJYXlzhPMTY0s6iFHekYfVJM9eiDRUbPqHN88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});